[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/login"
  to = "/.netlify/functions/auth/login"
  status = 200

[[redirects]]
  from = "/api/logout"
  to = "/.netlify/functions/auth/logout"
  status = 200

[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/auth/auth/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200